package com.synapse.social.studioasinc.shared.data.repository

import com.synapse.social.studioasinc.shared.data.crypto.SignalProtocolManager
import com.synapse.social.studioasinc.shared.data.crypto.models.EncryptedMessage
import com.synapse.social.studioasinc.shared.data.crypto.models.PreKeyBundle
import com.synapse.social.studioasinc.shared.data.datasource.SupabaseChatDataSource
import com.synapse.social.studioasinc.shared.data.dto.chat.MessageDto
import com.synapse.social.studioasinc.shared.data.local.database.CachedMessageDao
import com.synapse.social.studioasinc.shared.util.Logger
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Centralizes E2EE logic for chat messages.
 *
 * This class is responsible for:
 *
 * - Detecting encrypted messages
 * - Decrypting Signal Protocol messages
 * - Caching decrypted messages
 * - Creating Signal sessions
 * - Initializing the local E2EE identity
 * - Synchronizing the public key bundle with the server
 */
internal class ChatEncryptionHelper(
    private val signalProtocolManager: SignalProtocolManager?,
    private val dataSource: SupabaseChatDataSource,
    private val cachedMessageDao: CachedMessageDao?
) {

    /**
     * In-memory cache for decrypted message payloads.
     *
     * Key   = message ID
     * Value = decrypted JSON payload
     */
    val decryptedMessageCache =
        mutableMapOf<String, String>()

    // ============================================================
    // JSON HELPERS
    // ============================================================

    /**
     * Extracts the actual message content and optional media URL
     * from a decrypted JSON payload.
     *
     * Example:
     *
     * {
     *   "content": "Hello",
     *   "mediaUrl": "https://..."
     * }
     */
    private fun extractContent(
        jsonString: String
    ): Pair<String, String?> {

        return try {

            val jsonPayload =
                Json.parseToJsonElement(
                    jsonString
                ).jsonObject

            val content =
                jsonPayload["content"]
                    ?.jsonPrimitive
                    ?.content
                    ?: jsonString

            val mediaUrl =
                jsonPayload["mediaUrl"]
                    ?.jsonPrimitive
                    ?.content

            Pair(
                content,
                mediaUrl
            )

        } catch (_: Exception) {

            Pair(
                jsonString,
                null
            )
        }
    }

    /**
     * Determines whether a JSON object looks like the encrypted
     * recipient payload generated by SendMessageUseCase.
     *
     * Expected structure:
     *
     * {
     *   "userId": {
     *      "type": 3,
     *      "body": "..."
     *   }
     * }
     *
     * This method intentionally returns a non-null Boolean.
     */
    private fun isEncryptedPayload(
        jsonObject: JsonObject
    ): Boolean {

        val firstValue =
            jsonObject.values.firstOrNull()
                ?: return false

        if (firstValue !is JsonObject) {
            return false
        }

        return firstValue.containsKey("type") &&
                firstValue.containsKey("body")
    }

    /**
     * Returns the placeholder shown when an encrypted message
     * cannot be decrypted.
     */
    private fun encryptedPlaceholder(
        senderId: String,
        currentUserId: String
    ): String {

        return if (senderId == currentUserId) {
            "🔒 You sent an encrypted message"
        } else {
            "🔒 Encrypted message"
        }
    }

    // ============================================================
    // DECRYPT MESSAGE
    // ============================================================

    /**
     * Decrypts the message when the content contains a Signal
     * encrypted payload.
     *
     * The method uses:
     *
     * 1. Memory cache
     * 2. Local database cache
     * 3. Signal Protocol decryption
     */
    suspend fun MessageDto.decryptIfNecessary(
        currentUserId: String
    ): MessageDto {

        val messageId =
            this.id
                ?: return this

        // --------------------------------------------------------
        // 1. MEMORY CACHE
        // --------------------------------------------------------

        val memoryCached =
            decryptedMessageCache[messageId]

        if (memoryCached != null) {

            Logger.d(
                "E2EE_DECRYPT: Found message $messageId in memory cache",
                tag = "E2EE"
            )

            val extracted =
                extractContent(
                    memoryCached
                )

            return this.copy(
                content = extracted.first,
                mediaUrl =
                    extracted.second
                        ?: this.mediaUrl
            )
        }

        // --------------------------------------------------------
        // 2. LOCAL DATABASE CACHE
        // --------------------------------------------------------

        val dbCached =
            try {

                cachedMessageDao
                    ?.getMessages(
                        chatId ?: "",
                        200
                    )
                    ?.find {
                        it.id == messageId
                    }

            } catch (e: Exception) {

                Logger.w(
                    "E2EE_DECRYPT: Failed to read DB cache: ${e.message}",
                    tag = "E2EE"
                )

                null
            }

        val placeholders =
            setOf(
                "Message is encrypted",
                "🔒 Encrypted message",
                "🔒 You sent an encrypted message",
                "🔒 You sent an encrypted message (Copy)"
            )

        if (
            dbCached != null &&
            dbCached.content.isNotBlank() &&
            dbCached.content !in placeholders
        ) {

            Logger.d(
                "E2EE_DECRYPT: Found message $messageId in DB cache",
                tag = "E2EE"
            )

            decryptedMessageCache[
                messageId
            ] = dbCached.content

            return this.copy(
                content = dbCached.content,
                mediaUrl =
                    dbCached.mediaUrl
                        ?: this.mediaUrl
            )
        }

        // --------------------------------------------------------
        // 3. PARSE MESSAGE JSON
        // --------------------------------------------------------

        val jsonObject =
            try {

                Json.parseToJsonElement(
                    this.content
                ).jsonObject

            } catch (_: Exception) {

                // Normal plaintext message.
                return this
            }

        // --------------------------------------------------------
        // 4. CHECK WHETHER MESSAGE IS ENCRYPTED
        // --------------------------------------------------------

        val encryptedPayload =
            isEncryptedPayload(
                jsonObject
            )

        if (!encryptedPayload) {

            // Normal plaintext JSON.
            return this
        }

        // --------------------------------------------------------
        // 5. SIGNAL MANAGER
        // --------------------------------------------------------

        val manager =
            signalProtocolManager
                ?: return this.copy(
                    content =
                        encryptedPlaceholder(
                            senderId = this.senderId,
                            currentUserId = currentUserId
                        )
                )

        // --------------------------------------------------------
        // 6. GET CURRENT USER PAYLOAD
        // --------------------------------------------------------

        val myPayloadElement =
            jsonObject[currentUserId]

        if (myPayloadElement == null) {

            Logger.w(
                "E2EE_DECRYPT: No encrypted payload found for current user $currentUserId",
                tag = "E2EE"
            )

            return this.copy(
                content =
                    encryptedPlaceholder(
                        senderId = this.senderId,
                        currentUserId = currentUserId
                    )
            )
        }

        // --------------------------------------------------------
        // 7. DECODE ENCRYPTED MESSAGE
        // --------------------------------------------------------

        val myPayload =
            try {

                Json.decodeFromJsonElement(
                    EncryptedMessage.serializer(),
                    myPayloadElement
                )

            } catch (e: Exception) {

                Logger.e(
                    "E2EE_DECRYPT: Failed to decode encrypted payload for message $messageId",
                    tag = "E2EE",
                    throwable = e
                )

                return this.copy(
                    content =
                        encryptedPlaceholder(
                            senderId = this.senderId,
                            currentUserId = currentUserId
                        )
                )
            }

        // --------------------------------------------------------
        // 8. SIGNAL DECRYPTION
        // --------------------------------------------------------

        return try {

            val decryptedBytes =
                manager.decryptMessage(
                    senderId = this.senderId,
                    message = myPayload
                )

            val decryptedContent =
                decryptedBytes.decodeToString()

            Logger.d(
                "E2EE_DECRYPT: Successfully decrypted message $messageId",
                tag = "E2EE"
            )

            // Store the complete decrypted payload in memory.
            decryptedMessageCache[
                messageId
            ] = decryptedContent

            val extracted =
                extractContent(
                    decryptedContent
                )

            val content =
                extracted.first

            val mediaUrl =
                extracted.second

            // Save decrypted content to local cache.
            try {

                cachedMessageDao
                    ?.updateContent(
                        messageId,
                        content
                    )

            } catch (e: Exception) {

                Logger.w(
                    "E2EE_DECRYPT: Failed to update DB cache: ${e.message}",
                    tag = "E2EE"
                )
            }

            this.copy(
                content = content,
                mediaUrl =
                    mediaUrl
                        ?: this.mediaUrl
            )

        } catch (decryptError: Exception) {

            Logger.e(
                "E2EE_DECRYPT: Signal decryption failed for message $messageId",
                tag = "E2EE",
                throwable = decryptError
            )

            this.copy(
                content =
                    encryptedPlaceholder(
                        senderId = this.senderId,
                        currentUserId = currentUserId
                    )
            )
        }
    }

    // ============================================================
    // ENSURE SESSION
    // ============================================================

    /**
     * Ensures that a Signal Protocol session exists with a user.
     *
     * If a session does not exist, the user's public pre-key bundle
     * is fetched from Supabase and processed by Signal Protocol.
     */
    suspend fun ensureSession(
        userId: String,
        forceRebuild: Boolean = false
    ) {

        val manager =
            signalProtocolManager
                ?: throw IllegalStateException(
                    "SignalProtocolManager is null"
                )

        if (userId.isBlank()) {

            throw IllegalArgumentException(
                "Cannot establish E2EE session for empty user ID"
            )
        }

        // --------------------------------------------------------
        // EXISTING SESSION
        // --------------------------------------------------------

        if (
            manager.hasSession(userId) &&
            !forceRebuild
        ) {

            Logger.d(
                "E2EE_SESSION: Session already exists for user $userId",
                tag = "E2EE"
            )

            return
        }

        // --------------------------------------------------------
        // FORCE REBUILD
        // --------------------------------------------------------

        if (forceRebuild) {

            Logger.w(
                "E2EE_SESSION: Force rebuilding session for user $userId",
                tag = "E2EE"
            )

            try {

                manager.deleteSession(
                    userId
                )

            } catch (e: Exception) {

                Logger.w(
                    "E2EE_SESSION: Failed to delete old session: ${e.message}",
                    tag = "E2EE"
                )
            }
        }

        // --------------------------------------------------------
        // FETCH REMOTE PRE-KEY BUNDLE
        // --------------------------------------------------------

        Logger.d(
            "E2EE_SESSION: Fetching public key bundle for $userId",
            tag = "E2EE"
        )

        val keyDto =
            dataSource.getUserPublicKey(
                userId
            )

        if (keyDto == null) {

            Logger.e(
                "E2EE_SESSION: Public key bundle not found for $userId",
                tag = "E2EE"
            )

            throw IllegalStateException(
                "Recipient hasn't enabled E2EE"
            )
        }

        // --------------------------------------------------------
        // DECODE BUNDLE
        // --------------------------------------------------------

        val bundle =
            try {

                Json.decodeFromString<PreKeyBundle>(
                    keyDto.publicKey
                )

            } catch (e: Exception) {

                Logger.e(
                    "E2EE_SESSION: Invalid public key bundle for $userId",
                    tag = "E2EE",
                    throwable = e
                )

                throw IllegalStateException(
                    "Recipient has an invalid E2EE key bundle",
                    e
                )
            }

        // --------------------------------------------------------
        // VALIDATE BUNDLE
        // --------------------------------------------------------

        if (bundle.identityKey.isBlank()) {

            throw IllegalStateException(
                "Recipient identity key is missing"
            )
        }

        if (bundle.signedPreKeyPublic.isBlank()) {

            throw IllegalStateException(
                "Recipient signed pre-key is missing"
            )
        }

        if (bundle.signedPreKeySignature.isBlank()) {

            throw IllegalStateException(
                "Recipient signed pre-key signature is missing"
            )
        }

        if (bundle.registrationId <= 0) {

            throw IllegalStateException(
                "Recipient registration ID is invalid"
            )
        }

        if (bundle.deviceId <= 0) {

            throw IllegalStateException(
                "Recipient device ID is invalid"
            )
        }

        // --------------------------------------------------------
        // PROCESS SIGNAL BUNDLE
        // --------------------------------------------------------

        try {

            Logger.d(
                "E2EE_SESSION: Processing bundle for user $userId " +
                        "(registrationId=${bundle.registrationId}, " +
                        "deviceId=${bundle.deviceId}, " +
                        "preKeyId=${bundle.preKeyId}, " +
                        "signedPreKeyId=${bundle.signedPreKeyId})",
                tag = "E2EE"
            )

            manager.processPreKeyBundle(
                userId,
                bundle
            )

            if (!manager.hasSession(userId)) {

                throw IllegalStateException(
                    "Signal session was not created"
                )
            }

            Logger.d(
                "E2EE_SESSION: Session established successfully for $userId",
                tag = "E2EE"
            )

        } catch (e: Exception) {

            Logger.e(
                "E2EE_SESSION: Failed to establish session for $userId",
                tag = "E2EE",
                throwable = e
            )

            throw e
        }
    }

    // ============================================================
    // INITIALIZE E2EE
    // ============================================================

    /**
     * Initializes E2EE for the currently authenticated user.
     */
    suspend fun initializeE2EE(
        currentUserId: String?
    ): Result<Unit> {

        return try {

            val manager =
                signalProtocolManager
                    ?: return Result.failure(
                        IllegalStateException(
                            "SignalProtocolManager is null, E2EE not available"
                        )
                    )

            if (currentUserId.isNullOrBlank()) {

                return Result.failure(
                    IllegalStateException(
                        "User not authenticated, cannot initialize E2EE"
                    )
                )
            }

            Logger.d(
                "E2EE_INIT: Starting E2EE initialization for $currentUserId",
                tag = "E2EE"
            )

            // ----------------------------------------------------
            // LOCAL IDENTITY
            // ----------------------------------------------------

            val hasLocalKeys =
                manager.hasIdentity()

            // ----------------------------------------------------
            // REMOTE IDENTITY
            // ----------------------------------------------------

            val remoteKeyDto =
                try {

                    dataSource.getUserPublicKey(
                        currentUserId
                    )

                } catch (e: Exception) {

                    Logger.w(
                        "E2EE_INIT: Failed to fetch remote keys: ${e.message}",
                        tag = "E2EE"
                    )

                    null
                }

            val hasRemoteKeys =
                remoteKeyDto != null

            // ----------------------------------------------------
            // IDENTITY COMPARISON
            // ----------------------------------------------------

            var isIdentityMismatch =
                false

            if (
                hasLocalKeys &&
                hasRemoteKeys &&
                remoteKeyDto != null
            ) {

                try {

                    val localIdentity =
                        manager.getLocalIdentityKey()

                    val remoteBundle =
                        Json.decodeFromString<PreKeyBundle>(
                            remoteKeyDto.publicKey
                        )

                    if (
                        localIdentity !=
                        remoteBundle.identityKey
                    ) {

                        Logger.w(
                            "E2EE_INIT: Identity mismatch detected",
                            tag = "E2EE"
                        )

                        isIdentityMismatch =
                            true
                    }

                } catch (e: Exception) {

                    Logger.e(
                        "E2EE_INIT: Failed to compare identities",
                        tag = "E2EE",
                        throwable = e
                    )
                }
            }

            Logger.d(
                "E2EE_INIT: " +
                        "hasLocalKeys=$hasLocalKeys, " +
                        "hasRemoteKeys=$hasRemoteKeys, " +
                        "mismatch=$isIdentityMismatch",
                tag = "E2EE"
            )

            // ====================================================
            // CASE 1
            // LOCAL + REMOTE + SAME IDENTITY
            // ====================================================

            if (
                hasLocalKeys &&
                hasRemoteKeys &&
                !isIdentityMismatch
            ) {

                val registrationId =
                    manager.getLocalRegistrationId()

                Logger.d(
                    "E2EE_INIT: E2EE already initialized " +
                            "(registrationId=$registrationId)",
                    tag = "E2EE"
                )

                if (
                    manager.checkKeyRotationNeeded()
                ) {

                    Logger.w(
                        "E2EE_INIT: Key rotation recommended",
                        tag = "E2EE"
                    )
                }

                return Result.success(Unit)
            }

            // ====================================================
            // CASE 2
            // LOCAL EXISTS + REMOTE MISSING/MISMATCH
            // ====================================================

            if (
                hasLocalKeys &&
                (!hasRemoteKeys || isIdentityMismatch)
            ) {

                if (isIdentityMismatch) {

                    Logger.w(
                        "E2EE_INIT: Identity mismatch. " +
                                "Clearing local sessions.",
                        tag = "E2EE"
                    )

                    manager.deleteAllSessions()
                }

                Logger.d(
                    "E2EE_INIT: Building local E2EE bundle",
                    tag = "E2EE"
                )

                val bundle =
                    buildBundleFromLocalKeys()

                val bundleString =
                    Json.encodeToString(
                        bundle
                    )

                dataSource.uploadUserPublicKey(
                    bundleString
                )

                Logger.d(
                    "E2EE_INIT: E2EE bundle uploaded successfully",
                    tag = "E2EE"
                )

                return Result.success(Unit)
            }

            // ====================================================
            // CASE 3
            // NO LOCAL IDENTITY
            // ====================================================

            Logger.d(
                "E2EE_INIT: Generating new E2EE identity",
                tag = "E2EE"
            )

            val identity =
                manager.generateIdentityAndKeys()

            Logger.d(
                "E2EE_INIT: Identity generated " +
                        "(registrationId=${identity.registrationId})",
                tag = "E2EE"
            )

            val preKeys =
                manager.generateOneTimePreKeys(
                    startId = 1,
                    count = 100
                )

            if (preKeys.isEmpty()) {

                throw IllegalStateException(
                    "Failed to generate one-time pre-keys"
                )
            }

            Logger.d(
                "E2EE_INIT: Generated ${preKeys.size} one-time pre-keys",
                tag = "E2EE"
            )

            val firstPreKey =
                preKeys.first()

            val bundle =
                PreKeyBundle(
                    registrationId =
                        identity.registrationId,

                    deviceId =
                        1,

                    preKeyId =
                        firstPreKey.keyId,

                    preKeyPublic =
                        firstPreKey.publicKey,

                    signedPreKeyId =
                        identity.signedPreKeyId,

                    signedPreKeyPublic =
                        identity.signedPreKey,

                    signedPreKeySignature =
                        identity.signedPreKeySignature,

                    identityKey =
                        identity.identityKey
                )

            val bundleString =
                Json.encodeToString(
                    bundle
                )

            Logger.d(
                "E2EE_INIT: Uploading E2EE bundle",
                tag = "E2EE"
            )

            dataSource.uploadUserPublicKey(
                bundleString
            )

            Logger.d(
                "E2EE_INIT: E2EE initialization completed",
                tag = "E2EE"
            )

            Result.success(Unit)

        } catch (e: Exception) {

            Logger.e(
                "E2EE_INIT: Initialization failed: ${e.message}",
                tag = "E2EE",
                throwable = e
            )

            Result.failure(
                e
            )
        }
    }

    // ============================================================
    // BUILD LOCAL BUNDLE
    // ============================================================

    /**
     * Builds a new public bundle using the existing identity.
     *
     * The identity key itself is preserved while a fresh signed
     * pre-key and one-time pre-key batch are generated.
     */
    private suspend fun buildBundleFromLocalKeys():
        PreKeyBundle {

        val manager =
            signalProtocolManager
                ?: throw IllegalStateException(
                    "SignalProtocolManager is null"
                )

        val registrationId =
            manager.getLocalRegistrationId()

        val identityKey =
            manager.getLocalIdentityKey()

        val preKeys =
            manager.generateOneTimePreKeys(
                startId = 1,
                count = 100
            )

        if (preKeys.isEmpty()) {

            throw IllegalStateException(
                "Failed to generate one-time pre-keys"
            )
        }

        val identity =
            manager.generateIdentityAndKeys()

        val firstPreKey =
            preKeys.first()

        return PreKeyBundle(

            registrationId =
                registrationId,

            deviceId =
                1,

            preKeyId =
                firstPreKey.keyId,

            preKeyPublic =
                firstPreKey.publicKey,

            signedPreKeyId =
                identity.signedPreKeyId,

            signedPreKeyPublic =
                identity.signedPreKey,

            signedPreKeySignature =
                identity.signedPreKeySignature,

            identityKey =
                identityKey
        )
    }
}
